"use client";

import { useMemo } from "react";
import Link from "next/link";
import { Sparkles, MapPin, Route, ListChecks } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StateBadge } from "./state-badge";
import { LeaveByChip } from "./leave-by-chip";
import { SourceChip } from "./source-chip";
import type { Household } from "@/lib/schemas/household";

/**
 * Phase-4 shell. Real plan rendering arrives in phase 6. For now it
 * shows a graceful "standing by" state for a freshly onboarded household
 * and accepts a future plan prop.
 */
export function PlanPanel({
  household,
}: {
  household: Household | null;
}) {
  const hasHousehold = Boolean(household);

  return (
    <aside className="flex h-full flex-col overflow-hidden rounded-2xl border border-[var(--color-line-subtle)] bg-[var(--color-bg-panel)]/70 backdrop-blur-sm">
      <div className="flex items-center justify-between border-b border-[var(--color-line-subtle)]/70 px-5 py-4">
        <span className="text-[10.5px] font-medium uppercase tracking-[0.22em] text-[var(--color-text-muted)]">
          Current plan
        </span>
        <StateBadge state={hasHousehold ? "watch" : "watch"} size="sm" />
      </div>

      <div className="flex-1 overflow-y-auto p-5">
        {!hasHousehold ? (
          <EmptyState />
        ) : (
          <StandbyPlan household={household!} />
        )}
      </div>

      <div className="border-t border-[var(--color-line-subtle)]/70 px-5 py-3 text-[11px] text-[var(--color-text-muted)]">
        Plans are regenerated by Claude Opus 4.7. The deterministic
        fallback keeps things working offline.
      </div>
    </aside>
  );
}

function EmptyState() {
  return (
    <div className="flex h-full flex-col items-center justify-center text-center">
      <div className="mb-4 flex h-11 w-11 items-center justify-center rounded-full border border-[var(--color-line-subtle)] bg-[var(--color-bg-oled)]">
        <Sparkles
          className="h-4 w-4 text-[var(--color-ember)]"
          strokeWidth={1.75}
        />
      </div>
      <p className="max-w-[28ch] text-[14px] leading-relaxed text-[var(--color-text-secondary)]">
        Add your household to unlock a plan anchored to your home.
      </p>
      <Link href="/setup" className="mt-4">
        <Button size="sm" variant="ember">
          Start setup
        </Button>
      </Link>
    </div>
  );
}

function StandbyPlan({ household }: { household: Household }) {
  const primary = household.destinations[0];
  // Anchor stable "now" + leave-by target for this render so the countdown
  // doesn't churn every re-render and lint stays happy.
  const { leaveByIso, nowIso } = useMemo(() => {
    const now = new Date();
    const target = new Date(now.getTime() + 45 * 60 * 1000);
    return { nowIso: now.toISOString(), leaveByIso: target.toISOString() };
  }, []);

  return (
    <div className="space-y-5">
      {/* Hero line */}
      <div>
        <p className="font-display text-[22px] font-medium leading-tight tracking-[-0.01em] text-[var(--color-text-primary)]">
          Conditions are quiet.
          <br />
          <span className="text-[var(--color-text-secondary)]">
            Evacua is watching the signals for you.
          </span>
        </p>
        <div className="mt-3 flex flex-wrap items-center gap-2">
          <SourceChip source="nws" publishedAt={nowIso} confidence={0.9} />
          <SourceChip source="nifc" publishedAt={nowIso} confidence={0.88} />
        </div>
      </div>

      <LeaveByChip
        state="watch"
        targetIso={leaveByIso}
        className="w-full justify-between"
      />

      <SectionCard
        icon={MapPin}
        label="Destination"
        body={
          primary ? (
            <>
              <div className="text-[14px] text-[var(--color-text-primary)]">
                {primary.label || primary.address}
              </div>
              <div className="mt-0.5 text-[12.5px] text-[var(--color-text-muted)]">
                {primary.address}
              </div>
            </>
          ) : (
            <div className="text-[13px] text-[var(--color-text-muted)]">
              Add a destination during setup to preview a route.
            </div>
          )
        }
      />

      <SectionCard
        icon={Route}
        label="Route"
        body={
          <div className="space-y-2">
            <RouteRow
              label="Primary"
              road="—"
              eta="Route renders when a plan is active"
              selected
            />
            <RouteRow label="Backup" road="—" eta="" />
          </div>
        }
      />

      <SectionCard
        icon={ListChecks}
        label="Tasks"
        body={
          <ul className="space-y-1.5 text-[13px] leading-relaxed text-[var(--color-text-secondary)]">
            <li>Keep phones charged and vehicles topped up.</li>
            <li>Stage a go-bag near the door.</li>
            <li>Review meeting point with household.</li>
          </ul>
        }
      />
    </div>
  );
}

function SectionCard({
  icon: Icon,
  label,
  body,
}: {
  icon: React.ElementType;
  label: string;
  body: React.ReactNode;
}) {
  return (
    <section className="rounded-xl border border-[var(--color-line-subtle)] bg-[var(--color-bg-oled)]/40 p-4">
      <div className="mb-2 flex items-center gap-2 text-[10.5px] font-medium uppercase tracking-[0.2em] text-[var(--color-text-muted)]">
        <Icon className="h-3 w-3" strokeWidth={1.75} />
        {label}
      </div>
      {body}
    </section>
  );
}

function RouteRow({
  label,
  road,
  eta,
  selected = false,
}: {
  label: string;
  road: string;
  eta: string;
  selected?: boolean;
}) {
  return (
    <div
      className={
        "flex items-center justify-between rounded-lg border px-3 py-2 " +
        (selected
          ? "border-[var(--color-ember)]/40 bg-[var(--color-ember-soft)]/30"
          : "border-[var(--color-line-subtle)] bg-[var(--color-bg-panel)]/50")
      }
    >
      <div>
        <div className="text-[11px] font-medium uppercase tracking-[0.18em] text-[var(--color-text-muted)]">
          {label}
        </div>
        <div className="mt-0.5 text-[13px] text-[var(--color-text-primary)]">
          {road}
        </div>
      </div>
      <div className="max-w-[60%] text-right text-[12px] leading-tight text-[var(--color-text-secondary)]">
        {eta}
      </div>
    </div>
  );
}
